name: Running Tracker
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs: 
  update-readme-with-blog: 
    name: Update this repo's README with my Strava information
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: orafaelfragoso/run-tracker-workflow@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNNING_GOAL: ${{ secrets.RUNNING_GOAL }}
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_USER_ID: ${{ secrets.STRAVA_USER_ID }}